### ISSUE TITLE
Warning: Default property attribute 'assign' not appropriate for object

### ISSUE THREAD

**Issue by bivant** [wonderpush/wonderpush-ios-sdk#10]
xCode 11.5 (11E608c), WonderPush 3.3.3
WPInAppMessaging.h:55
```Swift
@property(nonatomic) id<WPInAppMessagingDisplay> messageDisplayComponent;
```
Pods/WonderPush/InAppMessages/Sources/Public/WPInAppMessaging.h:55:1: No 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed
Pods/WonderPush/InAppMessages/Sources/Public/WPInAppMessaging.h:55:1: Default property attribute 'assign' not appropriate for object

Proposed changes: specify **weak** attribute as in the 60-th line:
```Swift
@property(nonatomic, weak) id<WPInAppMessagingDisplayDelegate> delegate;

**Comment by stephanejais** [comment]
Fixed with `e1120eeb860c34ad8467dacc0c82bf7d6a0a24e5`
