### ISSUE TITLE
"Embedded binary is not signed with the same certificate as the parent app. Verify the embedded binary target's code sign settings match the parent app's."

### ISSUE THREAD

**Issue by lashermes** [wonderpush/wonderpush-ios-sdk#15]
Hi,

on Xcode if i test on real device, push notifications are working.
The provisioning profile use a certificate of type "Apple Development" (so in Debug, for testing on real device)

But if I want to publish to the Appstore (in release) : 
1. I change the provisioning profile which contains an "Apple Distribution" certificate
2. I create an Archive (Product -> Archive)
3. The build fails at the end with this message : 
"Embedded binary is not signed with the same certificate as the parent app. Verify the embedded binary target's code sign settings match the parent app's."

The WonderPushNotificationServiceExtension is configured to : "Automatically manage signing"
But this service is configured to have an "Apple Development" certificate

How to publish an app with the wonder push extension to the App Store ?

**Comment by ofavre** [comment]
Hi,

Do you use a framework like Cordova, Flutter or React Native or do you use a native Xcode project directly?

Can you send a screencapture of the "Signing & Capabilities" tab of both you app target and the Notification Service Extension target?
If necessary for privacy, use the chat on your WonderPush dashboard.

It should be configured this way:

* For the application target:
  > Automatically manage signing: Checked
  > Team: Your team name
  > Bundle Identifier: com.your.bundle.identifier
  > Provisioning Profile: Xcode Managed Profile
  > Signing Certificate: Apple Development: Your Name (YOURTEAMID)
* For the Notification Service Extension target:
  > Automatically manage signing: Checked
  > Team: Your team name
  > Bundle Identifier: com.your.bundle.identifier.WonderPushNotificationServiceExtension
  > Provisioning Profile: Xcode Managed Profile
  > Signing Certificate: Apple Development: Your Name (YOURTEAMID)

**Comment by lashermes** [comment]
> 

1. native Xcode project directly
2. App signing & capabilities
App: 
<img width="941" alt="Capture d’écran 2022-09-28 à 13 09 03" src="https://user-images.githubusercontent.com/53522372/192765493-c53f07d4-435c-491a-a669-12cfc5d5c8bd.png">

Service :
<img width="953" alt="Capture d’écran 2022-09-28 à 13 10 52" src="https://user-images.githubusercontent.com/53522372/192765379-0f0a36a2-53c3-4ce7-8bc3-137df01ba18a.png">

Error message now:
Archive -> Distribute App -> App Store Connect -> Upload -> Automatically manage signing : 
<img width="752" alt="Capture d’écran 2022-09-28 à 13 17 16" src="https://user-images.githubusercontent.com/53522372/192765932-9669f2da-9cd1-4dca-aedb-bd526911ff9d.png">

And I can't create an identifier (bundle ID) com.example.WonderPushNotificationServiceExtension

So I create a wildcard com.example.*
![Capture d’écran 2022-09-28 à 13 24 39](https://user-images.githubusercontent.com/53522372/192767160-3ae12666-6dc2-4a60-ac29-e9f7c5810561.png)

**Comment by ofavre** [comment]
> The app identifier "com.[…].WonderPushNotificationServiceExtension" cannot be registered to your development team because it is not available. Change your bundle identifier to a unique string to try again.

I believe this may be because that AppID was already used with another TeamID.
Maybe you still have access to that other TeamID and can either use that one, or go to it's associated App Store Connect page and remove the association with the AppID, to free it for your new TeamID.

Or as the message says, simply use another AppID for this extension.
Make sure to change the target id in your `Podfile` accordingly if you use Cocoapods.

Once fixed the second error message will probably disappear too.
