### ISSUE TITLE
Signing for "WonderPush-WonderPush" requires a development team

### ISSUE THREAD

**Issue by vochitan90** [wonderpush/wonderpush-ios-sdk#16]
Hi guys,

I'm using Xcode 14 and "@ionic-native/wonderpush": "^5.28.0",

From Xcode 14 - I'm facing a problem in Signing & Capabilities tab and the team property does not select value automatically (default value = None) everytime I **npm run build** and **npx cap sync**

![image](https://user-images.githubusercontent.com/8901498/196113892-6c1ca547-2f47-49f7-9746-ee0636c44148.png)

Error: Signing for "WonderPush-WonderPush" requires a development team. Select a development team in the Signing & Capabilities editor.

I have to chose the team manually to solve this problem.

Note that: I've never faced this problem before.

Any help would be appreciated. Thanks!

**Comment by luzemma** [comment]
Hi! I have the same issue with Flutter integration.

Do you have a solution, Wonderpush Team?

**Comment by ofavre** [comment]
Hi,

The recommended way to reach our support is via the chat available directly from your WonderPush dashboard.

For Cordova we recommend that you setup automatic provisioning as explained in our [quickstart guide](https://docs.wonderpush.com/docs/cordova-push-notifications-quickstart#i-classfa-fa-applei-ios---setup-automatic-provisioning).

Flutter does not overwrite the Xcode settings everytime, so as long as you do not delete the generated project, your settings will stick.

**Comment by vochitan90** [comment]
Hi @ofavre 

Because my project is using capacitor so the Cordova does not accepted.

![image](https://github.com/wonderpush/wonderpush-ios-sdk/assets/8901498/5a9ac3f1-2de9-47fd-9559-62f70e26680c)

I try to read this [Q&A](https://forum.ionicframework.com/t/ios-where-to-enable-codesignidentity-developmentteam-previously-set-in-cordova-build-json/230416)  and currently still not have the solution yet.
