### ISSUE TITLE
setClientId:secret: crashes app at launch 

### ISSUE THREAD

**Issue by rav013** [wonderpush/wonderpush-ios-sdk#2]
I found crash that appear when app set client id (`[WonderPush setClientId:secret:]`). I cannot reproduce the problem but it lays here:

```
if (!oldProperties || !oldPropertiesDate || !oldPropertiesAccessToken
        || ![oldProperties isEqualToDictionary:properties]
        || ![oldPropertiesAccessToken isEqualToString:sharedConfiguration.accessToken]
    ) {
```

The `oldProperties` is not `NSDictionary`, but `NSData`.
Call stack:
http://pastie.org/10872228

**Comment by ofavre** [comment]
A type check has been added, and a [new SDK version](https://github.com/wonderpush/wonderpush-ios-sdk/releases/tag/v1.2.1.0) is now published.

Thanks for reporting.
