### ISSUE TITLE
Pod install with use_frameworks! failure

### ISSUE THREAD

**Issue by dDomovoj** [wonderpush/wonderpush-ios-sdk#4]
pod install in this case will give next error message:
`The XXXX target has frameworks with conflicting names: wonderpush`

```
use_frameworks!
platform :ios, '7.0'

target 'Application' do
#adding swift/objc pods 
      pod 'WonderPush', '~> 2.0'
end

target 'PushNotificationServiceExtension' do
      pod 'WonderPush/NotificationServiceExtension', '~> 2.0'
end
```

Removing `use_frameworks!` fixes issue but makes using swift-written pods not possible.

**Comment by ofavre** [comment]
Can you try with the following:

```
platform :ios, '7.0'

target 'Application' do
    use_frameworks!
    pod 'WonderPush', '~> 2.2'
end

target 'PushNotificationServiceExtension' do
    pod 'WonderPush/NotificationServiceExtension', '~> 2.2'
end
```

I removed the toplevel `use_frameworks!` declaration to only include it in the application target, so that the extension does not use frameworks.

**Comment by dDomovoj** [comment]
Analyzing dependencies
[!] Unable to integrate the following embedded targets with their respective host targets (a host target is a "parent" target which embeds a "child" target like a framework or extension):

- Application (true) and PushNotificationServiceExtension (false) do not both set use_frameworks!.

**Comment by ofavre** [comment]
Can you take a look at the [`swift` branch of the demo application](https://github.com/wonderpush/wonderpush-ios-demo/tree/swift)?
It's working fine.

By the way, which version of cocoapods are you using?
```
$ pod --version
1.2.0
```

**Comment by dDomovoj** [comment]
1.2.1 and unfortunately still get this when

pod install
Analyzing dependencies
[!] Unable to integrate the following embedded targets with their respective host targets (a host target is a "parent" target which embeds a "child" target like a framework or extension):

- WonderPushDemo (true) and WonderPushNotificationServiceExtension (false) do not both set use_frameworks!.

**Comment by ofavre** [comment]
I've updated to 1.2.1 and got the same error. I'll try to address this.

Please use `pod _1.2.0_ install` in the meantime.
If you have an error that says `can't find gem cocoapods (= 1.2.0)` do `gem install cocoapods --version 1.2.0`.
