### ISSUE TITLE
*continue userActivity* not called due to wonderPush 

### ISSUE THREAD

**Issue by chlebta** [wonderpush/wonderpush-ios-sdk#9]
Setting up `WonderPush.setupDelegate(for: application)` in AppDelegate cause this strange behavior  : 

`func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void)` is not called AnyMore

**Comment by ahmetws** [comment]
I think I have the same problem with 
`func application(_ application: UIApplication,
                   supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {}`

@chlebta have you solved the issue?

**Comment by stephanejais** [comment]
Some frameworks like Firebase do method swizzling and can interfere with the way WonderPush listens to delegate methods. See https://docs.wonderpush.com/docs/troubleshooting-ios#i-get-that-message-warning-method-swizzling-detected
